
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
source /home/vagrant/.rvm/scripts/rvm

[ -z "$TMUX" ] && export TERM=xterm=256color

